version: "3.9"

x-template: &template
  build:
    context: .
    dockerfile: docker/local/app/Dockerfile
  env_file:
    - .env
  depends_on:
    - db
    - redis
  volumes:
    - .:/app
  networks:
    - default

services:
  app:
    container_name: app-weather
    <<: *template
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"

  db:
    container_name: db-weather
    image: postgres:alpine
    environment:
      POSTGRES_USER: open_weather
      POSTGRES_PASSWORD: not_bad_weather
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - default

  redis:
    image: redis:latest
    container_name: redis-weather
    restart: unless-stopped
    volumes:
      - ./data/redis_db:/data
    ports:
      - "6379:6379"
    networks:
      - default

networks:
  default:
    driver: bridge